export const MANHUA  =  "Manhua";
export const MANGA  =  "Manga";
export const MANHWA  =  "Manhwa";
export const NOVELA  =  "Novela";
export const ONE_SHOT  =  "One shot";
export const DOUJINSHI  =  "Doujinshi";
export const OEL  =  "Oel";

export const NO_MIEMBRO = "0";
export const SOLICITUD_ENVIADA = "1";
export const RECHAZADO = "2";
export const ACEPTADO = "3";
export const EXPULSADO = "4";




// Auth
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';

// Error
export const MENSAJE_ERROR = 'MENSAJE_ERROR';

// Grupo 
export const INSERTAR_GRUPO_EXITOSO = 'INSERTAR_GRUPO_EXITOSO';

export const OBTENER_GRUPO = 'OBTENER_GRUPO';
export const OBTENER_GRUPOS = 'OBTENER_GRUPOS';

export const INSERTAR_SOLICITUD = 'INSERTAR_SOLICITUD';
export const OBTENER_SOLICITUDES = 'OBTENER_SOLICITUDES';
export const OBTENER_SOLICITUD = "OBTENER_SOLICITUD";
export const ACTUALIZAR_SOLICITUD = 'ACTUALIZAR_SOLICITUD';
export const OBTENER_MIEMBROS = 'OBTENER_MIEMBROS';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const OBTENER_STATS = 'OBTENER_STATS';
export const OBTENER_TIPO_SOLICITUDES = 'OBTENER_TIPO_SOLICITUDES';

export const OBTENER_SEGUIDORES = 'OBTENER_SEGUIDORES';
export const SEGUIR_GRUPO = 'SEGUIR_GRUPO';
export const DEJAR_DE_SEGUIR_GRUPO = 'DEJAR_DE_SEGUIR_GRUPO';

//Perfil
export const OBTENER_PERFIL = 'OBTENER_PERFIL';
export const ACTUALIZAR_PERFIL = 'ACTUALIZAR_PERFIL';

//directorio
export const OBTENER_SERIES = 'OBTENER_SERIES';
export const FILTRAR = 'FILTRAR';

//Serie
export const SUBIR_SERIE = 'SUBIR_SERIE';

export const OBTENER_SERIE  = "OBTENER_SERIE";
export const OBTENER_CAPITULOS  = "OBTENER_CAPITULOS";
export const OBTENER_GENEROS_SERIE = "OBTENER_GENEROS_SERIE";
export const OBTENER_VOTOS = "OBTENER_VOTOS";

export const SUBIR_VOTO_SERIE = "SUBIR_VOTO_SERIE";

export const OBTENER_VISUALIZACIONES_SERIE = "OBTENER_VISUALIZACIONES_SERIE";
export const INSERTAR_VISUALIZACIONE_SERIE = "INSERTAR_VISUALIZACIONE_SERIE";

//Genero
export const OBTENER_GENEROS  = "OBTENER_GENEROS";
export const OBTENER_GENERO = "OBTENER_GENERO";
export const SUBIR_GENERO = "SUBIR_GENERO";

//Paginas
export const OBTENER_PAGINAS = "OBTENER_PAGINAS";
export const SET_CAPITULO_ID = "SET_CAPITULO_ID";

//Reacciones
export const OBTENER_REACCIONES = "OBTENER_REACCIONES";
export const SUBIR_REACCION = "SUBIR_REACCION";
export const OBTENER_REACCIONES_USUARIO = "OBTENER_REACCIONES_USUARIO";
export const OBTENER_SERIES_POR_REACCION_USUARIO = "OBTENER_SERIES_POR_REACCION_USUARIO";