
// Auth
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const CERRAR_SESION = 'CERRAR_SESION';


// Grupo 
export const INSERTAR_GRUPO_EXITOSO = 'INSERTAR_GRUPO_EXITOSO';
export const REGISTRO_GRUPO_ERROR = 'REGISTRO_GRUPO_ERROR';

export const OBTENER_GRUPO = 'OBTENER_GRUPO';
export const OBTENER_GRUPOS = 'OBTENER_GRUPOS';
export const OBTENER_GRUPOS_ERROR = 'OBTENER_GRUPOS_ERROR';

export const INSERTAR_SOLICITUD = 'INSERTAR_SOLICITUD';
export const INSERTAR_SOLICITUD_ERROR = 'INSERTAR_SOLICITUD_ERROR';
