
import './Header.css'
import './App.css'
import './Perfil.css'
import './Subirmanga.css'
import './Footer.css'
import './Terms.css'
import './Modal.css'
import './Manga.css'
import './Panel.css'
import './Scanlation.css'
import './GroupScans.css'
import './Directory.css'